version: '3.4'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped

  clamav:
    image: clamav
    build: clamav/
    container_name: clamav
    restart: unless-stopped

  haraka:
    image: haraka
    build: haraka/
    container_name: haraka
    restart: unless-stopped
    ports:
      - "2525:25"
    links:
      - mongodb
      - clamav
