version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped

  clamd:
    image: clamav/clamav:unstable
    container_name: clamd
    restart: unless-stopped
    environment:
      - "CLAMAV_NO_FRESHCLAMD=true"
      - "CLAMAV_NO_MILTERD=true"

  haraka:
    image: haraka
    build: haraka/
    container_name: haraka
    restart: unless-stopped
    ports:
      - "2525:25"
    links:
      - mongodb
      - clamd
