version: '2.0'
services:
  fw:
    build: .
    ports:
      - "0.0.0.0:17777:17777/udp"
      - "0.0.0.0:17778:17778/udp"
    volumes:
      - ./data:/data
    restart: unless-stopped
    mem_limit: 1000m
    ulimits:
      memlock: -1
    cap_add:
      - CAP_NET_ADMIN
      - CAP_SYS_ADMIN
