version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: -c shared_preload_libraries=pg_cron -c cron.database_name=xar -c shared_buffers=512MB -c max_locks_per_transaction=16000
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=xar

volumes:
  pg_data:
